language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt checkStyle
sudo: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start